DFE-Digital/fh-referral-api

- src/FamilyHubs.ReferralApi.Api/.dockerfile
> Latest Docker File Update

- .dockerfile
> Docker file update

- src/FamilyHubs.ReferralApi.Api/appsettings.json
> Appsetting fix

- src/FamilyHubs.ReferralApi.Api/appsettings.json
> appsettings

- src/FamilyHubs.ReferralApi.Api/Endpoints/MinimalReferralEndPoints.cs
- src/FamilyHubs.ReferralApi.Api/Program.cs
Modifies Seeding for Production
> Modifies Seeding for Production

- src/FamilyHubs.ReferralApi.Api/Commands/SetReferralStatus/SetReferralStatusCommand.cs
- src/FamilyHubs.ReferralApi.Api/Commands/SetReferralStatus/SetReferralStatusCommandValidator.cs
- src/FamilyHubs.ReferralApi.Api/Commands/UpdateReferral/UpdateReferralCommand.cs
- src/FamilyHubs.ReferralApi.Api/Commands/UpdateReferral/UpdateReferralCommandValidator.cs
- src/FamilyHubs.ReferralApi.Api/Endpoints/MinimalReferralEndPoints.cs
- src/FamilyHubs.ReferralApi.Core/Entities/ReferralStatus.cs
- src/FamilyHubs.ReferralApi.Core/Events/ReferralStatusCreatedEvent.cs
- src/FamilyHubs.ReferralApi.Core/Interfaces/Commands/ISetReferralStatusCommand.cs
- src/FamilyHubs.ReferralApi.Core/Interfaces/Commands/IUpdateReferralCommand.cs
- src/FamilyHubs.ReferralApi.Core/Interfaces/Events/IReferralStatusCreatedEvent.cs
- src/FamilyHubs.ReferralApi.Infrastructure/Persistence/Repository/ReferralSeedData.cs
- tests/FamilyHubs.ReferralApi.FunctionalTests/WhenUsingReferralsApiUnitTests.cs
- tests/FamilyHubs.ReferralApi.UnitTests/WhenUsingReferralCommands.cs
Added additional API End Points
> Added additional API End Points

- src/FamilyHubs.ReferralApi.Api/Commands/UpdateReferral/UpdateReferralCommand.cs
- src/FamilyHubs.ReferralApi.Api/DatabaseContextFactory.cs
- src/FamilyHubs.ReferralApi.Api/Migrations/20221215150932_AddTextAndRejectionReasonColumns.Designer.cs
- src/FamilyHubs.ReferralApi.Api/Migrations/20221215150932_AddTextAndRejectionReasonColumns.cs
- src/FamilyHubs.ReferralApi.Api/Queries/GetReferrals/GetReferralByIdCommand.cs
- src/FamilyHubs.ReferralApi.Api/Queries/GetReferrals/GetReferralsByOrganisationIdCommand.cs
- src/FamilyHubs.ReferralApi.Api/Queries/GetReferrals/GetReferralsByReferrerCommand.cs
- src/FamilyHubs.ReferralApi.Api/appsettings.json
- src/FamilyHubs.ReferralApi.Core/Entities/Referral.cs
- src/FamilyHubs.ReferralApi.Core/FamilyHubs.ReferralApi.Core.csproj
- src/FamilyHubs.ReferralApi.Infrastructure/Persistence/Repository/ApplicationDbContext.cs
- src/FamilyHubs.ReferralApi.Infrastructure/Persistence/Repository/ReferralSeedData.cs
- tests/FamilyHubs.ReferralApi.FunctionalTests/WhenUsingReferralsApiUnitTests.cs
- tests/FamilyHubs.ReferralApi.Infrastructure.Tests/BaseEfRepositoryTestFixture.cs
- tests/FamilyHubs.ReferralApi.UnitTests/BaseCreateDbUnitTest.cs
- tests/FamilyHubs.ReferralApi.UnitTests/WhenUsingReferralCommands.cs
Added Referral Column Encryption
Added Reason For Rejection
> Added Referral Column Encryption

- src/FamilyHubs.ReferralApi.Api/CommandMessageConsumer.cs
- src/FamilyHubs.ReferralApi.Api/CurrentUserService.cs
- src/FamilyHubs.ReferralApi.Api/RabbitMqSettings.cs
- src/FamilyHubs.ReferralApi.Infrastructure/Persistence/Repository/CachedRepository.cs
- tests/FamilyHubs.ReferralApi.FunctionalTests/WhenUsingReferralsApiUnitTests.cs
- tests/FamilyHubs.ReferralApi.UnitTests/WhenConfiguringServices.cs
- tests/FamilyHubs.ReferralApi.UnitTests/WhenUsingCachedRepository.cs
- tests/FamilyHubs.ReferralApi.UnitTests/WhenUsingReferralCommands.cs
- tests/FamilyHubs.ReferralApi.UnitTests/WhenValidatingReferralCommands.cs
- tests/FamilyHubs.ReferralApi.UnitTests/WhenValidatingReferralStatusCommand.cs
> Adding additional unit tests

- src/FamilyHubs.ReferralApi.Api/CommandMessageConsumer.cs
- src/FamilyHubs.ReferralApi.Api/Commands/CreateReferral/CreateReferralCommand.cs
- src/FamilyHubs.ReferralApi.Api/Commands/UpdateReferral/UpdateReferralCommand.cs
- src/FamilyHubs.ReferralApi.Api/Endpoints/MinimalReferralEndPoints.cs
- src/FamilyHubs.ReferralApi.Api/FamilyHubs.ReferralApi.Api.csproj
- src/FamilyHubs.ReferralApi.Api/Queries/GetReferrals/GetReferralByIdCommand.cs
- src/FamilyHubs.ReferralApi.Api/Queries/GetReferrals/GetReferralsByOrganisationIdCommand.cs
- src/FamilyHubs.ReferralApi.Api/Queries/GetReferrals/GetReferralsByReferrerCommand.cs
- src/FamilyHubs.ReferralApi.Core/AutoMappingProfiles.cs
- src/FamilyHubs.ReferralApi.Core/FamilyHubs.ReferralApi.Core.csproj
- src/FamilyHubs.ReferralApi.Core/Interfaces/Commands/ICreateReferralCommand.cs
- src/FamilyHubs.ReferralApi.Core/Interfaces/Commands/IUpdateReferralCommand.cs
- src/FamilyHubs.ReferralApi.Infrastructure/FamilyHubs.ReferralApi.Infrastructure.csproj
- tests/FamilyHubs.ReferralApi.FunctionalTests/FamilyHubs.ReferralApi.FunctionalTests.csproj
- tests/FamilyHubs.ReferralApi.FunctionalTests/WhenUsingReferralsApiUnitTests.cs
- tests/FamilyHubs.ReferralApi.Infrastructure.Tests/FamilyHubs.ReferralApi.Infrastructure.Tests.csproj
- tests/FamilyHubs.ReferralApi.UnitTests/FamilyHubs.ReferralApi.UnitTests.csproj
- tests/FamilyHubs.ReferralApi.UnitTests/WhenUsingReferralCommands.cs
Upgraded to .Net 7 and all dependencies
> Upgraded to .Net 7 and all dependencies

- src/FamilyHubs.Referral.Core/Queries/GetReferrals/GetReferralsHandlerBase.cs
Fixed Paginated List Total record count
> Fixed Paginated List Total record count

- src/FamilyHubs.Referral.Core/Commands/CreateReferral/CreateReferralCommand.cs
Includes:
* dispose of the transaction scope when the using scope ends (otherwise we could potentially run out of connections or memory)
> FHG-3216 Improvements

- src/FamilyHubs.Referral.Core/Queries/GetReferrals/GetReferralsHandlerBase.cs
> Modify Sorting

- src/FamilyHubs.Referral.Api/Endpoints/MinimalReferralEndPoints.cs
- src/FamilyHubs.Referral.Core/Commands/CreateReferral/CreateReferralCommandValidator.cs
- src/FamilyHubs.Referral.Core/Commands/UpdateReferral/UpdateReferralCommand.cs
- src/FamilyHubs.Referral.Core/Commands/UpdateReferral/UpdateReferralCommandValidator.cs
- src/FamilyHubs.Referral.Core/Queries/GetReferrals/GetReferralsByReferrerByReferrerIdCommand.cs
- src/FamilyHubs.Referral.Data/Migrations/20230615115854_ReferrerIdNeedsToBeSupplied.Designer.cs
- src/FamilyHubs.Referral.Data/Migrations/20230615115854_ReferrerIdNeedsToBeSupplied.cs
- src/FamilyHubs.Referral.Data/Repository/ApplicationDbContext.cs
- src/FamilyHubs.Referral.Data/Repository/ReferralSeedData.cs
- tests/FamilyHubs.ReferralApi.FunctionalTests/WhenUsingReferralsApiUnitTests.cs
- tests/FamilyHubs.ReferralApi.Integration.Tests/TestDataProvider.cs
- tests/FamilyHubs.ReferralApi.UnitTests/BaseCreateDbUnitTest.cs
- tests/FamilyHubs.ReferralApi.UnitTests/WhenUsingReferralCommands.cs
- tests/FamilyHubs.ReferralApi.UnitTests/WhenValidatingReferralCommands.cs
FHG-3689 Modify Referrer Id to be Not Null, Add Api to get referrals by Referrer
> FHG-3689 Modify Referrer Id to be Not Null, Add Api to get referrals by Referrer

- src/FamilyHubs.Referral.Api/Endpoints/MinimalReferralEndPoints.cs
- src/FamilyHubs.Referral.Core/Commands/SetReferralStatus/SetReferralStatusCommand.cs
- src/FamilyHubs.Referral.Core/Commands/UpdateReferral/UpdateReferralCommand.cs
- src/FamilyHubs.Referral.Data/Entities/Referral.cs
- src/FamilyHubs.Referral.Data/Repository/ApplicationDbContextInitialiser.cs
- tests/FamilyHubs.ReferralApi.FunctionalTests/WhenUsingReferralsApiUnitTests.cs
- tests/FamilyHubs.ReferralApi.Integration.Tests/WhenSettingReferralStatus.cs
- tests/FamilyHubs.ReferralApi.Integration.Tests/WhenUsingUpdateReferral.cs
- tests/FamilyHubs.ReferralApi.UnitTests/WhenUsingReferralCommands.cs
- tests/FamilyHubs.ReferralApi.UnitTests/WhenValidatingReferralStatusCommand.cs
Fixed Referral update and extended api/referralStatus to include reason for declining
> Fixed Referral update and extended api/referralStatus to include reason for declining

- src/FamilyHubs.Referral.Core/Commands/UpdateReferral/UpdateReferralCommand.cs
- src/FamilyHubs.Referral.Data/Entities/Referral.cs
> Fix for Update Referral

- src/FamilyHubs.Referral.Api/Endpoints/MinimalReferralEndPoints.cs
- src/FamilyHubs.Referral.Core/Queries/GetReferrals/GetReferralByServiceIdStatusIdRecipientIdReferrerIdCommand.cs
- src/FamilyHubs.Referral.Core/Queries/GetReferrals/GetReferralsByOrganisationIdCommand.cs
- src/FamilyHubs.Referral.Core/Queries/GetReferrals/GetReferralsByReferrerByReferrerIdCommand.cs
- src/FamilyHubs.Referral.Core/Queries/GetReferrals/GetReferralsByReferrerCommand.cs
- tests/FamilyHubs.ReferralApi.Integration.Tests/WhenUsingGetReferral.cs
- tests/FamilyHubs.ReferralApi.UnitTests/WhenUsingReferralCommands.cs
- tests/FamilyHubs.ReferralApi.UnitTests/WhenValidatingReferralCommands.cs
Excludes Declined Referrals except when specifically asked for
> Excludes Declined Referrals except when specifically asked for

- src/FamilyHubs.Referral.Api/Endpoints/MinimalReferralEndPoints.cs
- tests/FamilyHubs.ReferralApi.FunctionalTests/BaseWhenUsingOpenReferralApiUnitTests.cs
- tests/FamilyHubs.ReferralApi.FunctionalTests/WhenUsingReferralsApiUnitTests.cs
Restrict access to get referral by Id
> Restrict access to get referral by Id

- src/FamilyHubs.Referral.Api/Endpoints/MinimalReferralEndPoints.cs
- src/FamilyHubs.Referral.Api/StartupExtensions.cs
- src/FamilyHubs.Referral.Data/FamilyHubs.Referral.Data.csproj
- tests/FamilyHubs.ReferralApi.FunctionalTests/BaseWhenUsingOpenReferralApiUnitTests.cs
- tests/FamilyHubs.ReferralApi.FunctionalTests/WhenUsingReferralsApiUnitTests.cs
> Add Authentication Policy

- src/FamilyHubs.Referral.Data/Repository/ReferralSeedData.cs
> Amended Secondary Sort Order

- src/FamilyHubs.Referral.Data/Entities/ReferralService.cs
- src/FamilyHubs.Referral.Data/FamilyHubs.Referral.Data.csproj
- src/FamilyHubs.Referral.Data/Migrations/20230623104212_AddServiceUrlToSchema.Designer.cs
- src/FamilyHubs.Referral.Data/Migrations/20230623104212_AddServiceUrlToSchema.cs
- src/FamilyHubs.Referral.Data/Repository/ReferralSeedData.cs
- tests/FamilyHubs.ReferralApi.FunctionalTests/WhenUsingReferralsApiUnitTests.cs
- tests/FamilyHubs.ReferralApi.Integration.Tests/TestDataProvider.cs
- tests/FamilyHubs.ReferralApi.UnitTests/WhenUsingReferralCommands.cs
> Added Service url

- src/FamilyHubs.Referral.Api/StartupExtensions.cs
- src/FamilyHubs.Referral.Data/FamilyHubs.Referral.Data.csproj
- src/FamilyHubs.Referral.Data/Repository/ApplicationDbContextInitialiser.cs
- tests/FamilyHubs.ReferralApi.FunctionalTests/WhenUsingReferralsApiUnitTests.cs
Encrypt ReasonForSupport  and EngageWithFamily in seed data
> Encrypt ReasonForSupport  and EngageWithFamily in seed data

- src/FamilyHubs.Referral.Api/appsettings.json
> Updated appsettings.json

- src/FamilyHubs.Referral.Core/Commands/ProcessGridEventCommand.cs
- tests/FamilyHubs.ReferralApi.UnitTests/WhenUsingProcessUserGridEventCommands.cs
> Added additional logging

- src/FamilyHubs.Referral.Api/StartupExtensions.cs
- src/FamilyHubs.Referral.Core/Commands/CreateOrUpdateOrganisation/CreateOrUpdateOrganisationCommand.cs
- src/FamilyHubs.Referral.Core/Commands/CreateOrUpdateService/CreateOrUpdateServiceCommand.cs
- src/FamilyHubs.Referral.Core/Commands/ProcessGridEventCommand.cs
- tests/FamilyHubs.ReferralApi.FunctionalTests/WhenUsingUserAccountsApiTests.cs
- tests/FamilyHubs.ReferralApi.Integration.Tests/WhenCreateOrUpdateService.cs
- tests/FamilyHubs.ReferralApi.UnitTests/WhenUsingCreateOrUpdateOrganisationCommand.cs
- tests/FamilyHubs.ReferralApi.UnitTests/WhenUsingCreateOrUpdateServiceCommand.cs
- tests/FamilyHubs.ReferralApi.UnitTests/WhenUsingProcessUserGridEventCommands.cs
Added the additional ability to Add or Update Services
> Added the additional ability to Add or Update Services

- src/FamilyHubs.Referral.Api/StartupExtensions.cs
- src/FamilyHubs.Referral.Api/appsettings.json
- src/FamilyHubs.Referral.Core/Commands/CreateReferral/CreateReferralCommand.cs
- src/FamilyHubs.Referral.Data/FamilyHubs.Referral.Data.csproj
- tests/FamilyHubs.ReferralApi.FunctionalTests/WhenUsingReferralsApiUnitTests.cs
- tests/FamilyHubs.ReferralApi.Integration.Tests/WhenUsingCreateReferralCommand.cs
- tests/FamilyHubs.ReferralApi.UnitTests/WhenUsingReferralCommands.cs
Modified the Create Referral Command
> Modified the Create Referral Command

- src/FamilyHubs.Referral.Core/Commands/CreateOrUpdateService/CreateOrUpdateServiceCommand.cs
- src/FamilyHubs.Referral.Core/Commands/CreateReferral/CreateReferralCommand.cs
- src/FamilyHubs.Referral.Core/Interfaces/Commands/ICreateOrUpdateServiceCommand.cs
- tests/FamilyHubs.ReferralApi.UnitTests/WhenUsingReferralCommands.cs
Modified Create Referral to use UserAccount Id
> Modified Create Referral to use UserAccount Id

- src/FamilyHubs.Referral.Api/FamilyHubs.Referral.Api.csproj
- src/FamilyHubs.Referral.Core/FamilyHubs.Referral.Core.csproj
- src/FamilyHubs.Referral.Data/FamilyHubs.Referral.Data.csproj
- tests/FamilyHubs.ReferralApi.FunctionalTests/BaseWhenUsingOpenReferralApiUnitTests.cs
- tests/FamilyHubs.ReferralApi.FunctionalTests/FamilyHubs.Referral.FunctionalTests.csproj
- tests/FamilyHubs.ReferralApi.FunctionalTests/WhenUsingReferralsApiUnitTests.cs
- tests/FamilyHubs.ReferralApi.Integration.Tests/FamilyHubs.Referral.Integration.Tests.csproj
- tests/FamilyHubs.ReferralApi.UnitTests/FamilyHubs.Referral.UnitTests.csproj
Updated All NuGet Packages
Fixed Functional Tests
> Updated All NuGet Packages

- src/FamilyHubs.Referral.Data/Interceptors/AuditableEntitySaveChangesInterceptor.cs
- tests/FamilyHubs.ReferralApi.Integration.Tests/DataIntegrationTestBase.cs
- tests/FamilyHubs.ReferralApi.UnitTests/BaseCreateDbUnitTest.cs
Adds the Logged on User when Database Changes are made
> Adds the Logged on User when Database Changes are made

- src/FamilyHubs.Referral.Api/StartupExtensions.cs
- src/FamilyHubs.Referral.Core/ConnectTelemetryPiiRedactor.cs
> Added PII Redactor
